AWSTemplateFormatVersion: 2010-09-09
Description: Creates an S3 bucket for hosting a Static HTML/CSS website
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # Bucket names must be globally unique
      BucketName: <PUT_YOUR_BUCKETNAME_HERE>
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
    # delete bucket when deleting the stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: <PUT_YOUR_BUCKETNAME_HERE>
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - <PUT_YOUR_BUCKETNAME_HERE>
                - /*
